ALTER TABLE learning_goal
    ADD COLUMN bloom_level VARCHAR(32)
        CHECK (bloom_level IN ('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE')),
    ADD COLUMN solo_level VARCHAR(32)
        CHECK (solo_level IN ('PRESTRUCTURAL', 'UNISTRUCTURAL', 'MULTISTRUCTURAL', 'RELATIONAL', 'EXTENDED_ABSTRACT'));
