import React, { useState } from "react";
import { saveAs } from "file-saver";
import { ActivityBlock, LearningGoalPlan, WorkshopSession, WorkshopInput, SlideData } from "@/lib/workshop-generator";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Clock, Target, ArrowLeft, Download, CheckCircle2, ChevronDown, Check, X, AlertTriangle, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { toast } from "@/hooks/use-toast";
import { phaseEmojis, getStepEmoji, getMechanicDescription, DEFAULT_ACTIVITIES, MODE_COLORS, getPhaseMode, getSectionMode, getStepMode } from "@/lib/constants";

// Removed duplicate local declarations

interface Props {
  session: WorkshopSession;
  goals?: LearningGoalPlan[];
  meta: WorkshopInput;
  slidesCache: Record<number, SlideData[]>;
  onBack: () => void;
  onDone: () => void;
}

const fmtTime = (m: number) => {
  const h = Math.floor(m / 60);
  const mm = (m % 60).toString().padStart(2, "0");
  return `${h.toString().padStart(2, "0")}:${mm}`;
};

export default function WorkshopFinalReview({ session, goals = [], meta, slidesCache, onBack, onDone }: Props) {
  const [isExporting, setIsExporting] = useState(false);

  const totalDuration = session.blocks.reduce((s, b) => s + (b.duration || 0), 0);

  // Compute running start times
  let cursor = 0;
  const rows = session.blocks.map((block) => {
    const start = cursor;
    cursor += block.duration;
    return { block, start: fmtTime(start), end: fmtTime(cursor) };
  });

  const downloadDeck = async () => {
    setIsExporting(true);
    toast({ title: "Preparing Deck…", description: "Combining cached slides and generating any missing ones." });
    try {
      const allCachedSlides = session.blocks.flatMap((_, i) => slidesCache[i] ?? []);
      const hasAllCached = session.blocks.every((_, i) => !!slidesCache[i]);

      let blob: Blob;
      if (hasAllCached && allCachedSlides.length > 0) {
        const res = await fetch(import.meta.env.BASE_URL + "api/workshop/export/pptx-assemble", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ session, meta, prebuiltSlides: allCachedSlides }),
        });
        if (!res.ok) throw new Error("Assembly failed");
        blob = await res.blob();
      } else {
        const res = await fetch(import.meta.env.BASE_URL + "api/workshop/export/pptx", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ session, meta, goals }),
        });
        if (!res.ok) throw new Error("Generation failed");
        blob = await res.blob();
      }

      const safeName = (session.title || session.learningGoal || "workshop").slice(0, 40).replace(/[^a-z0-9]+/gi, "_").toLowerCase();
      saveAs(blob, `${safeName}_slides.pptx`);
      toast({ title: "Slides Downloaded", description: hasAllCached ? "Assembled from cache (fast!)." : "Generated by AI." });
    } catch (e) {
      toast({ title: "Download failed", description: e instanceof Error ? e.message : "Unknown error", variant: "destructive" });
    } finally {
      setIsExporting(false);
    }
  };

  const downloadPdf = async () => {
    setIsExporting(true);
    toast({ title: "Generating PDF…" });
    try {
      const res = await fetch(import.meta.env.BASE_URL + "api/workshop/export/pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ session, meta, goals }),
      });
      if (!res.ok) throw new Error("Failed to generate PDF");
      const blob = await res.blob();
      const safeName = (session.learningGoal || "workshop").slice(0, 40).replace(/[^a-z0-9]+/gi, "_").toLowerCase();
      saveAs(blob, `${safeName}_session.pdf`);
      toast({ title: "PDF downloaded" });
    } catch (e) {
      toast({ title: "Download failed", description: e instanceof Error ? e.message : "Unknown error", variant: "destructive" });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="space-y-6 pb-20">
      <Card className="border-border/60 shadow-lg bg-surface flex flex-col max-w-5xl mx-auto w-full">
        {/* Header Block */}
        <div className="p-6 pb-2">
          <div className="font-display font-bold text-3xl mb-2 flex items-center justify-between gap-4">
            <span>{session.title || "Workshop Session Plan"}</span>
          </div>
          <div className="flex items-center gap-x-6 gap-y-2 flex-wrap text-sm text-muted-foreground font-body">
            <span className="flex items-center gap-1.5 font-medium"><Clock className="h-4 w-4 text-primary/60" /> {meta.duration || totalDuration} min</span>
            <span className="flex items-center gap-1.5 font-medium"><Users className="h-4 w-4 text-primary/60" /> {meta.participants} participants{session.studentBackground ? `, ${session.studentBackground}` : ""}</span>
          </div>

          <div className="mt-5 space-y-4">
            <div>
              <h3 className="font-body font-semibold flex items-center gap-2 mb-1"><Target className="h-4 w-4 text-primary" /> Learning Goals</h3>
              <ul className="text-sm font-body text-foreground/80 flex flex-col gap-1.5 list-none">
                {goals && goals.length > 0 ? goals.map((g, idx) => (
                  <li key={idx} className="flex items-start gap-1.5">
                    <span className="text-primary/60 mt-0.5">•</span>
                    <span className="leading-snug">{g.goal}</span>
                  </li>
                )) : (
                  <li className="flex items-start gap-1.5">
                    <span className="text-primary/60 mt-0.5">•</span>
                    <span className="leading-snug">{session.learningGoal}</span>
                  </li>
                )}
              </ul>
            </div>

            {session.prerequisites && (
              <div>
                <h3 className="font-body font-semibold flex items-center gap-2 mb-1"><Target className="h-4 w-4 text-primary" /> Prerequisites</h3>
                <ul className="text-sm font-body text-foreground/80 flex flex-wrap gap-x-4 gap-y-1.5 list-none">
                  {session.prerequisites?.split(';').filter(p => p.trim() !== '').map((prereq, idx) => (
                    <li key={idx} className="flex items-start gap-1.5 max-w-full">
                      <span className="text-primary/60 mt-0.5">•</span>
                      <span className="leading-snug text-muted-foreground">{prereq.trim()}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>

        {/* Timetable */}
        <div className="flex-1 px-2 sm:px-6 py-6 pb-8">
          <div className="mx-auto max-w-4xl">


            <div className="relative mt-2">
              <Accordion type="multiple" className="flex flex-col">
                {rows.map(({ block, start, end }, i) => {
                  const mode = getPhaseMode(block.phase);
                  const modeColors = MODE_COLORS[mode];
                  const isBreak = mode === "break";
                  
                  const nextBlock = i < rows.length - 1 ? rows[i+1].block : null;
                  const nextMode = nextBlock ? getPhaseMode(nextBlock.phase) : mode;
                  const nextModeColors = MODE_COLORS[nextMode];
                  
                  const gradientStr = `linear-gradient(to bottom, ${modeColors.dot}, ${nextModeColors.dot})`;
                  const dashedStr = `repeating-linear-gradient(to bottom, ${modeColors.dot}, ${modeColors.dot} 6px, transparent 6px, transparent 12px)`;
                  // Gap below this block encodes its duration on the timeline
                  const gapBelow = i < rows.length - 1 ? Math.max(12, block.duration * 5) : 0;
                  
                  const nextIsSmall = nextBlock && (nextBlock.phase === "BREAK" || nextBlock.phase === "BUFFER" || nextBlock.phase === "ARRIVE");
                  const nextDot = nextIsSmall ? 18 : 26;
                  
                  const tagsContent = (() => {
                    const allMethods = Array.from(new Set([
                      ...(block.methods || []),
                      ...(block.sections || []).flatMap(s => s.methods || [])
                    ])).filter(m => m && !m.toLowerCase().includes("lecture") && !m.toLowerCase().includes("presentation"));

                    if (allMethods.length === 0) return null;

                    return (
                        <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar shrink-0 ml-2">
                          <div className="h-4 w-[1px] bg-border/60 mx-1 shrink-0 hidden sm:block"></div>
                          {allMethods.map((m, j) => (
                            <TooltipProvider key={`meth-${j}`}>
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <div 
                                    style={{ backgroundColor: modeColors.badgeBg, color: modeColors.badgeText }}
                                    className="inline-flex items-center justify-center whitespace-nowrap rounded-full h-5 px-2.5 text-[0.75rem] font-semibold shrink-0 cursor-help"
                                  >
                                    {m}
                                  </div>
                                </TooltipTrigger>
                                <TooltipContent side="top" className="max-w-[250px] text-xs font-body font-normal">
                                  {getMechanicDescription(m)}
                                </TooltipContent>
                              </Tooltip>
                            </TooltipProvider>
                          ))}
                        </div>
                    );
                  })();

                  const innerContent = (
                      <div className="relative flex items-center w-full text-left">
                        {/* Time label column: 3.5rem (w-14) */}
                        <div className="w-14 shrink-0 flex flex-col justify-center text-right hidden sm:flex font-mono text-sm pr-2"
                             style={{ color: block.duration >= 10 ? 'var(--hestia-primary)' : 'var(--hestia-text-muted)', fontWeight: block.duration >= 10 ? 700 : 400 }}>
                          {block.duration}m
                        </div>

                        {/* Spine column: 2rem (w-8) */}
                        <div className="w-8 shrink-0 flex flex-col justify-center items-center relative hidden sm:flex self-stretch">
                          {/* Dot */}
                          <div className="absolute top-1/2 -translate-y-1/2 w-3 h-3 rounded-full shadow-sm z-10" 
                               style={{ backgroundColor: modeColors.dot, border: '1px solid white' }} />
                        </div>

                        {/* The block — fixed height, gap below encodes duration */}
                        <div 
                          className={`transition-all rounded-xl ${block.phase === "BREAK" || block.phase === "BUFFER" || block.phase === "ARRIVE" ? "px-3" : "px-4"} flex items-center gap-2 shrink-0`}
                          style={{
                            height: block.phase === "BREAK" || block.phase === "BUFFER" || block.phase === "ARRIVE" ? "36px" : "44px",
                            backgroundColor: modeColors.bgTint,
                            border: isBreak ? `1.5px dashed ${modeColors.border}` : `1px solid rgba(0,0,0,0.08)`,
                            boxShadow: isBreak ? "none" : "0 1px 4px rgba(0,0,0,0.07)",
                          }}
                        >
                          <span className="text-base shrink-0">{phaseEmojis[block.phase] || "✨"}</span>
                          <span className="font-body text-sm font-medium text-foreground whitespace-nowrap">{block.phaseLabel}</span>
                          {tagsContent}
                          {block.phase !== "BREAK" && <ChevronDown className="h-4 w-4 text-muted-foreground transition-transform duration-200 shrink-0 hidden sm:block ml-1" />}
                        </div>
                          </div>
                      );

                      if (block.phase === "BREAK") {
                        return (
                          <div 
                            key={block.blockId || i} 
                            className="border-0 relative bg-transparent mb-[var(--gap-below)]" 
                            style={{ '--gap-below': `${gapBelow}px` } as React.CSSProperties}
                          >
                            {/* Timeline spine for BREAK */}
                            {i < rows.length - 1 && (
                              <div 
                                className="absolute w-[2px] z-0 opacity-60 hidden sm:block transition-all duration-300"
                                style={{ 
                                  backgroundColor: modeColors.dot, 
                                  top: '18px', 
                                  left: '71px',
                                  bottom: `calc(-1 * (var(--gap-below) + ${nextDot}px))`
                                }} 
                              />
                            )}
                            {innerContent}
                          </div>
                        );
                      }

                      return (
                        <AccordionItem 
                          key={block.blockId || i} 
                          value={`item-${block.blockId || i}`} 
                          className="border-0 relative bg-transparent group/item transition-all duration-300 data-[state=closed]:mb-[var(--gap-below)] data-[state=open]:mb-6" 
                          style={{ 
                            '--gap-below': `${gapBelow}px`,
                            '--closed-bottom': `calc(-1 * (var(--gap-below) + ${nextDot}px))`,
                            '--open-bottom': `calc(-1 * (24px + ${nextDot}px))`
                          } as React.CSSProperties}
                        >
                          {/* Timeline spine */}
                          {i < rows.length - 1 && (
                            <div 
                              className="absolute w-[2px] z-0 opacity-60 hidden sm:block transition-all duration-300 group-data-[state=closed]/item:bottom-[var(--closed-bottom)] group-data-[state=open]/item:bottom-[var(--open-bottom)]"
                              style={{ 
                                backgroundColor: modeColors.dot, 
                                top: '26px', 
                                left: '71px' 
                              }} 
                            />
                          )}
                          <AccordionTrigger className="w-full py-1 hover:no-underline [&>svg]:hidden group focus:outline-none">
                            {innerContent}
                          </AccordionTrigger>
                          <AccordionContent className="pl-0 sm:pl-[5.5rem] pr-0 pb-4 pt-2 relative z-10">
                            {block.sections && block.sections.length > 0 && (
                              <div className="space-y-4">
                                {block.sections.map((section, sIdx) => {
                                  const sectionMode = getSectionMode(section.title || "", mode);
                                  const secColors = MODE_COLORS[sectionMode];
                                  
                                  return (
                                    <div key={sIdx} className="relative pl-6">
                                      {/* Sub-section chip */}
                                      {block.phase === "LEARNING_CYCLE" && section.title && (
                                        <div className="mb-2">
                                          <span 
                                            className="inline-flex font-mono text-[0.75rem] font-semibold uppercase tracking-[0.07em] px-2.5 py-0.5 rounded-md"
                                            style={{ backgroundColor: secColors.badgeBg, color: secColors.badgeText }}
                                          >
                                            {section.title}
                                          </span>
                                        </div>
                                      )}
                                      
                                      <div className="relative">
                                        {/* Sub Timeline track */}
                                        <div className="absolute top-2 bottom-2 left-[-16px] w-[1.5px]" style={{ backgroundColor: secColors.border, opacity: 0.25 }} />
                                        
                                        <div className="space-y-1.5">
                                          {(section.steps || []).map((step, stepIdx) => {
                                            const match = step.match(/^(\d+)\s*(?:min|m)(?:utes?)?\s*(?:—|-|:)\s*(.*)/i);
                                            const timeVal = match ? match[1] : "";
                                            let contentText = match ? match[2] : step;
                                            const subEmoji = getStepEmoji(contentText);
                                            const stepMode = getStepMode(contentText, sectionMode);
                                            const stepColors = MODE_COLORS[stepMode];

                                            return (
                                              <div key={stepIdx} className="relative flex items-center gap-2.5 group">
                                                {/* Sub dot */}
                                                <div 
                                                  className="absolute left-[-19.5px] top-1/2 -translate-y-1/2 w-2 h-2 rounded-full z-10" 
                                                  style={{ backgroundColor: stepColors.dot, opacity: 0.8, border: '1px solid white' }} 
                                                />
                                                
                                                {/* Time outside */}
                                                {timeVal ? (
                                                  <div 
                                                    className="w-7 shrink-0 text-[11px] font-mono font-medium text-right pr-0.5" 
                                                    style={{ color: stepColors.border }}
                                                  >
                                                    {timeVal}m
                                                  </div>
                                                ) : (
                                                  <div className="w-7 shrink-0" />
                                                )}

                                                {/* Content box */}
                                                <div 
                                                  className={`flex-1 px-3 py-2 text-sm font-body text-foreground/90 leading-relaxed flex items-center gap-2 ${contentText.toLowerCase().startsWith('activity') ? 'rounded-3xl' : 'rounded-lg'}`}
                                                  style={{
                                                    backgroundColor: stepColors.bgTint,
                                                    borderWidth: '1px',
                                                    borderStyle: contentText.toLowerCase().startsWith('prompt') ? 'dashed' : 'solid',
                                                    borderColor: 'color-mix(in srgb, var(--hestia-text) 10%, transparent)',
                                                    borderLeftWidth: '3px',
                                                    borderLeftStyle: (contentText.toLowerCase().startsWith('explain') && section.title?.toLowerCase().includes('practice')) ? 'dotted' : 'solid',
                                                    borderLeftColor: contentText.toLowerCase().startsWith('prompt') ? 'var(--hestia-phase-evaluate)' : contentText.toLowerCase().startsWith('activity') ? 'var(--hestia-phase-setup)' : stepColors.border,
                                                  }}
                                                >
                                                  {subEmoji && <span className="opacity-80 shrink-0">{subEmoji}</span>}
                                                  <span className="flex-1 min-w-0">{contentText}</span>
                                                </div>
                                              </div>
                                            );
                                          })}
                                        </div>
                                      </div>
                                    </div>
                                  );
                                })}
                              </div>
                            )}
                          </AccordionContent>
                        </AccordionItem>
                      );
                    })}
                  </Accordion>
                </div>
          </div>
        </div>

        {/* Omitted goals warning */}
        {session.omittedGoals && session.omittedGoals.length > 0 && (
          <div className="m-4 rounded-lg border border-amber-400/60 bg-amber-50/60 dark:bg-amber-950/30 dark:border-amber-500/40 px-4 py-3 space-y-2">
            <div className="flex items-start gap-2">
              <AlertTriangle className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
              <div className="flex-1">
                <p className="text-sm font-body font-semibold text-amber-800 dark:text-amber-300">
                  Not all learning goals could be covered
                </p>
                <p className="text-xs font-body text-amber-700 dark:text-amber-400 mt-0.5">
                  The following goal{session.omittedGoals.length > 1 ? "s were" : " was"} left out because there was not enough time to cover {session.omittedGoals.length > 1 ? "them" : "it"} meaningfully within the session duration. Consider reducing other goals or increasing the session time.
                </p>
              </div>
            </div>
            <ul className="ml-6 space-y-1">
              {session.omittedGoals.map((g, i) => (
                <li key={i} className="text-xs font-body text-amber-800 dark:text-amber-300 flex items-start gap-1.5">
                  <span className="text-amber-500 mt-0.5">•</span>
                  {g}
                </li>
              ))}
            </ul>
          </div>
        )}
        {/* Sticky Footer Bar */}
        <div className="sticky bottom-4 z-30 mx-4 mb-4 rounded-xl border border-border/80 bg-surface backdrop-blur-md shadow-2xl p-3 flex items-center justify-between gap-4 mt-6 transition-all">
          <Button
            variant="outline"
            size="sm"
            onClick={onBack}
            className="gap-2 font-body shrink-0 bg-transparent border-[1.5px] border-primary text-primary hover:bg-primary/5 transition-all duration-150"
          >
            <ArrowLeft className="h-4 w-4" /> Previous
          </Button>

          <div className="flex items-center gap-2 flex-wrap justify-end">
            <Button size="sm" variant="outline" onClick={downloadPdf} disabled={isExporting} className="gap-2 transition-all duration-150">
              <Download className="h-3.5 w-3.5" /> PDF Timetable
            </Button>
            <Button size="sm" variant="outline" onClick={downloadDeck} disabled={isExporting} className="gap-2 transition-all duration-150">
              <Download className="h-3.5 w-3.5" /> PPTX Slides
            </Button>
            <Button
            size="sm"
            onClick={onDone}
            className="gap-2 shadow-md hover:shadow-lg bg-primary text-primary-foreground font-semibold shrink-0 rounded-lg transition-all duration-150"
          >
            <CheckCircle2 className="h-3.5 w-3.5" /> Save & Export
          </Button>
          </div>
        </div>
      </Card>
    </div>
  );
}
