import React, { useState, useEffect, useCallback, useMemo } from "react";
import { saveAs } from "file-saver";
import { WorkshopSession, WorkshopInput, LearningGoalPlan, ActivityBlock, SlideData } from "@/lib/workshop-generator";
import { ArrowLeft, ArrowRight, Download, CheckCircle2, Presentation, ListChecks, Check, ChevronDown, ChevronUp, Loader2, X, ChevronLeft, ChevronRight, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import { SlideWorkstation } from "./SlideWorkstation";

interface Props {
  session: WorkshopSession;
  goals?: LearningGoalPlan[];
  meta: WorkshopInput;
  completedTasks?: string[];
  slidesCache: Record<number, SlideData[]>;
  setSlidesCache: React.Dispatch<React.SetStateAction<Record<number, SlideData[]>>>;
  onUpdateTasks?: (tasks: string[], isAllDone: boolean) => void;
  onBack: () => void;
  onDone: (tasks?: string[]) => void;
}

import { phaseEmojis, getMechanicDescription } from "@/lib/constants";

export default function WorkshopPreparation({ session, goals = [], meta, completedTasks: initialTasks = [], slidesCache, setSlidesCache, onUpdateTasks, onBack, onDone }: Props) {
  const [completedTasks, setCompletedTasks] = useState<Set<string>>(new Set(initialTasks));
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({});
  const [loadingSlides, setLoadingSlides] = useState<number | null>(null);
  const [openSlideDialog, setOpenSlideDialog] = useState<number | null>(null);
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);
  const [showMechanics, setShowMechanics] = useState(false);
  const [isKanbanOpen, setIsKanbanOpen] = useState(false);
  const [isSlideOpen, setIsSlideOpen] = useState(true);

  // getMechanicDescription imported from constants

  // Keyboard navigation for lightbox
  useEffect(() => {
    if (lightboxIndex === null || openSlideDialog === null) return;
    const slides = slidesCache[openSlideDialog] ?? [];
    const handler = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") setLightboxIndex(i => i !== null ? Math.min(i + 1, slides.length - 1) : null);
      if (e.key === "ArrowLeft") setLightboxIndex(i => i !== null ? Math.max(i - 1, 0) : null);
      if (e.key === "Escape") setLightboxIndex(null);
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [lightboxIndex, openSlideDialog, slidesCache]);

  const closeLightbox = useCallback(() => setLightboxIndex(null), []);
  const closeDialog = useCallback(() => { setOpenSlideDialog(null); setLightboxIndex(null); }, []);

  const allPrepItems = useMemo(() => {
    if (!session?.blocks) return [];
    
    const baseItems: any[] = [];
    const contentTasks: string[] = [];
    const activityTasks: string[] = [];
    const materialTasks: string[] = [];
    
    session.blocks.forEach((block, index) => {
        const phase = (block.phase || "").toUpperCase();
        const labelUpper = (block.phaseLabel || block.phase || "").toUpperCase();
        const label = block.phaseLabel || block.phase || `Block ${index + 1}`;
        
        const isIntro = phase.includes("WELCOME") || phase.includes("SETUP") || phase.includes("INTRODUCTION") || phase === "INTRO" || phase === "ARRIVE" || labelUpper.includes("WELCOME") || labelUpper.includes("SETUP") || labelUpper.includes("INTRODUCTION") || labelUpper.includes("ARRIVE");
        const isClosing = phase.includes("WRAP") || phase.includes("CLOSING") || phase.includes("CONCLUSION") || phase.includes("SUMMARY") || labelUpper.includes("WRAP") || labelUpper.includes("CLOSING") || labelUpper.includes("CONCLUSION") || labelUpper.includes("SUMMARY");
        const isCheck = phase.includes("CHECK") || labelUpper.includes("CHECK");
        const isActivity = phase.includes("LEARNING") || phase.includes("CYCLE") || phase.includes("ACTIVATE") || phase === "CUSTOM" || isCheck || labelUpper.includes("LEARNING") || labelUpper.includes("CYCLE") || labelUpper.includes("ACTIVATE");
        const isBreak = phase === "BREAK" || phase === "BUFFER" || labelUpper.includes("BREAK");

        if (isIntro) {
             // Welcome slides are now generated by the LLM, so no manual placeholder replacement is needed
        }
        else if (isClosing) {
             // Summary/Closing slides are now generated by the LLM, so no manual placeholder replacement is needed
        }
        else if (isBreak) {
             // Break slides are pre-generated
        }
        else if (isActivity) {
             if (isCheck) {
                 activityTasks.push(`"${label}" (Review Quiz & Debrief)`);
             } else {
                 contentTasks.push(`"${label}" (Insert Lecture Content)`);
                 activityTasks.push(`"${label}" (Review Activity Prompt)`);
             }
        } else {
             contentTasks.push(`"${label}" (Insert Lecture Content)`);
        }
        
        const materials = [...(block.materials || []), ...(block.sections || []).flatMap(s => s.materials || [])]
            .filter(Boolean)
            .map(m => String(m).trim())
            .filter(m => {
                const lower = m.toLowerCase();
                return !lower.includes("slide") && !lower.includes("prompt card") && !lower.includes("attendance sheet");
            });
        const uniqueMaterials = Array.from(new Set(materials));
        if (uniqueMaterials.length > 0) {
             materialTasks.push(`"${label}": ${uniqueMaterials.join(', ')}`);
        }
    });

    if (contentTasks.length > 0) {
        baseItems.unshift({
            id: 'all-content',
            label: 'Insert your own lecture content into placeholder slides',
            category: 'content',
            subTodos: contentTasks.map((task, i) => ({ id: `cnt-sub-${i}`, label: task }))
        });
    }

    if (activityTasks.length > 0) {
        baseItems.push({
            id: 'all-activities',
            label: 'Review and finalize all generated activities, quizzes, and debriefs',
            category: 'activity',
            subTodos: activityTasks.map((task, i) => ({ id: `act-sub-${i}`, label: task }))
        });
    }

    if (materialTasks.length > 0) {
        baseItems.push({
            id: 'all-materials',
            label: 'Prepare all additional materials for the session',
            category: 'prep',
            subTodos: materialTasks.map((task, i) => ({ id: `mat-sub-${i}`, label: task }))
        });
    }

    return baseItems;
  }, [session?.blocks]);

  const toggleTask = (taskId: string) => {
    setCompletedTasks(prev => {
      const next = new Set(prev);
      const item = allPrepItems.find((i: any) => i.id === taskId);
      
      if (next.has(taskId)) {
        next.delete(taskId);
        if (item && item.subTodos) item.subTodos.forEach((sub: any) => next.delete(sub.id));
      } else {
        next.add(taskId);
        if (item && item.subTodos) item.subTodos.forEach((sub: any) => next.add(sub.id));
      }
      
      const isAllDone = allPrepItems.length > 0 && allPrepItems.every((item: any) => next.has(item.id));
      onUpdateTasks?.(Array.from(next), isAllDone);
      return next;
    });
  };

  const toggleSubTask = (parentId: string, subId: string) => {
    setCompletedTasks(prev => {
      const next = new Set(prev);
      if (next.has(subId)) next.delete(subId); else next.add(subId);
      
      const item = allPrepItems.find((i: any) => i.id === parentId);
      if (item && item.subTodos) {
        const allSubDone = item.subTodos.every((sub: any) => next.has(sub.id));
        if (allSubDone) next.add(parentId);
        else next.delete(parentId);
      }

      const isAllDone = allPrepItems.length > 0 && allPrepItems.every((item: any) => next.has(item.id));
      onUpdateTasks?.(Array.from(next), isAllDone);
      return next;
    });
  };

  const toggleCollapsed = (key: string) => {
    setCollapsed(prev => ({ ...prev, [key]: !prev[key] }));
  };

  // Fetch slides for a single block (with cache)
  const fetchBlockSlides = async (blockIndex: number, block: ActivityBlock) => {
    if (slidesCache[blockIndex]) {
      setOpenSlideDialog(blockIndex);
      return;
    }
    setLoadingSlides(blockIndex);
    try {
      const res = await fetch(import.meta.env.BASE_URL + "api/workshop/export/block-slides", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ block, meta }),
      });
      if (!res.ok) throw new Error("Server returned " + res.status);
      const slides: SlideData[] = await res.json();
      setSlidesCache(prev => ({ ...prev, [blockIndex]: slides }));
      setOpenSlideDialog(blockIndex);
    } catch (e) {
      toast({ title: "Slides failed", description: e instanceof Error ? e.message : "Unknown error", variant: "destructive" });
    } finally {
      setLoadingSlides(null);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div>
          <h2 className="font-display font-semibold text-2xl">Class Preparation</h2>
          <p className="text-muted-foreground font-body text-sm mt-1">Review materials, track your prep, and preview slides for each block.</p>
        </div>
      </div>

      <SlideWorkstation
        session={session}
        meta={meta}
        goals={goals}
        slidesCache={slidesCache}
        setSlidesCache={setSlidesCache}
        onPreview={() => setOpenSlideDialog(-1)} // -1 means all slides
        isOpen={isSlideOpen}
        setIsOpen={setIsSlideOpen}
      />



      {/* Slide Grid Dialog */}
      {openSlideDialog !== null && (openSlideDialog === -1 || slidesCache[openSlideDialog]) && (() => {
        const dialogSlides = openSlideDialog === -1
          ? session.blocks.flatMap((_, i) => slidesCache[i] ?? [])
          : slidesCache[openSlideDialog] ?? [];
        if (dialogSlides.length === 0) return null;

        const dialogTitle = openSlideDialog === -1 ? "All Lecture Slides" : session.blocks[openSlideDialog]?.phaseLabel;

        return (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" onClick={closeDialog}>
            <div
              className="bg-surface rounded-2xl shadow-2xl border border-border/50 w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden"
              onClick={e => e.stopPropagation()}
            >
              <div className="flex items-center justify-between p-5 border-b border-border/50">
                <div>
                  <h2 className="font-display text-2xl font-bold">
                    {dialogTitle} — Slide Preview
                  </h2>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {dialogSlides.length} slides · click a slide to enlarge · use ← → to navigate
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="ghost" size="icon" onClick={closeDialog}>
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              </div>
              <div className="overflow-y-auto p-5 grid grid-cols-1 md:grid-cols-2 gap-5">
                {dialogSlides.map((slide, idx) => (
                  <button
                    key={idx}
                    onClick={() => setLightboxIndex(idx)}
                    className="relative overflow-hidden min-h-[220px] bg-surface border border-slate-200 shadow-sm rounded-lg flex flex-col p-5 text-left cursor-pointer hover:border-primary/50 hover:ring-1 hover:ring-primary/30 hover:shadow-md transition-all group"
                  >
                    <div className="border-b border-slate-100 pb-2.5 mb-3 w-full">
                      <h3 className="text-sm font-bold text-slate-800 leading-snug text-left">{slide.title}</h3>
                      {slide.subtitle && (
                        <p className="text-xs font-semibold text-primary mt-1 text-left">{slide.subtitle}</p>
                      )}
                    </div>
                    <ul className="space-y-2 flex-1 w-full">
                      {slide.bullets?.map((b, j) => (
                        <li key={j} className="text-xs text-slate-600 leading-relaxed flex items-start gap-2">
                          <span className="text-primary/60 mt-0.5 shrink-0">•</span>
                          <span>{b}</span>
                        </li>
                      ))}
                    </ul>
                    {slide.notes && (
                      <div className="mt-3 pt-2 border-t border-slate-100 text-xs text-slate-400 italic line-clamp-2">{slide.notes}</div>
                    )}
                    {/* Magnify hint — contained within the button via relative/overflow-hidden */}
                    <div className="absolute inset-0 bg-primary/0 group-hover:bg-primary/5 transition-colors flex items-center justify-center opacity-0 group-hover:opacity-100 backdrop-blur-[1px]">
                      <span className="bg-surface text-primary text-xs font-semibold px-3 py-1.5 rounded-full shadow-sm">Click to Enlarge</span>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        );
      })()}

      {/* Lightbox: single slide full-size with arrows */}
      {lightboxIndex !== null && openSlideDialog !== null && (() => {
        const slides = openSlideDialog === -1
          ? session.blocks.flatMap((_, i) => slidesCache[i] ?? [])
          : slidesCache[openSlideDialog] ?? [];
        const slide = slides[lightboxIndex];
        if (!slide) return null;
        const blockLabel = openSlideDialog === -1 ? "Slide Workstation" : session.blocks[openSlideDialog]?.phaseLabel ?? "";
        return (
          <div
            className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 backdrop-blur-md p-6"
            onClick={closeLightbox}
          >
            {/* Prev arrow */}
            {lightboxIndex > 0 && (
              <button
                className="absolute left-4 top-1/2 -translate-y-1/2 bg-foreground/10 hover:bg-foreground/25 transition-colors rounded-full p-3 text-foreground z-10"
                onClick={e => { e.stopPropagation(); setLightboxIndex(i => i !== null ? i - 1 : null); }}
              >
                <ChevronLeft className="h-6 w-6" />
              </button>
            )}

            {/* Slide card */}
            <div
              className="bg-surface rounded-2xl shadow-2xl flex flex-col w-full max-w-3xl aspect-video p-10 relative"
              onClick={e => e.stopPropagation()}
            >
              {/* Top accent */}
              <div className="absolute top-0 left-0 w-full h-1 rounded-t-2xl bg-gradient-to-r from-primary to-primary/40" />
              {/* Block breadcrumb */}
              <p className="text-xs font-semibold text-primary/60 uppercase tracking-widest mb-3">
                {blockLabel} · {lightboxIndex + 1} / {slides.length}
              </p>
              <h2 className="font-display text-2xl font-bold text-slate-800 mb-1 leading-tight">{slide.title}</h2>
              {slide.subtitle && (
                <p className="text-lg font-semibold text-primary mb-5">{slide.subtitle}</p>
              )}
              {!slide.subtitle && <div className="mb-5"></div>}
              <ul className="space-y-3 flex-1">
                {slide.bullets?.map((b, j) => (
                  <li key={j} className="flex items-start gap-3 text-slate-700">
                    <span className="text-primary mt-1 shrink-0">•</span>
                    <span className="text-lg leading-snug">{b}</span>
                  </li>
                ))}
              </ul>
              {slide.notes && (
                <div className="mt-4 pt-3 border-t border-slate-100 text-xs text-slate-400 italic">
                  📝 {slide.notes}
                </div>
              )}
            </div>

            {/* Next arrow */}
            {lightboxIndex < slides.length - 1 && (
              <button
                className="absolute right-4 top-1/2 -translate-y-1/2 bg-foreground/10 hover:bg-foreground/25 transition-colors rounded-full p-3 text-foreground z-10"
                onClick={e => { e.stopPropagation(); setLightboxIndex(i => i !== null ? i + 1 : null); }}
              >
                <ChevronRight className="h-6 w-6" />
              </button>
            )}

            {/* Dot indicators */}
            <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex gap-1.5">
              {slides.map((_, idx) => (
                <button
                  key={idx}
                  onClick={e => { e.stopPropagation(); setLightboxIndex(idx); }}
                  className={`h-1.5 rounded-full transition-all ${idx === lightboxIndex ? "w-6 bg-foreground" : "w-1.5 bg-foreground/40 hover:bg-foreground/60"
                    }`}
                />
              ))}
            </div>

            {/* Close */}
            <button
              className="absolute top-4 right-4 bg-foreground/10 hover:bg-foreground/25 transition-colors rounded-full p-2 text-foreground"
              onClick={closeLightbox}
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        );
      })()}

      <div className="mt-8 flex justify-between items-center bg-surface p-4 rounded-xl border shadow-sm">
        <Button variant="outline" onClick={onBack} className="gap-2 font-body shrink-0 bg-transparent border-[1.5px] border-primary text-primary hover:bg-primary/5 transition-all duration-150">
          <ArrowLeft className="h-4 w-4" /> Timetable
        </Button>
        <Button onClick={() => onDone(Array.from(completedTasks))} className="gap-2 shadow-md hover:shadow-lg bg-primary text-primary-foreground font-semibold shrink-0 rounded-lg transition-all duration-150">
          Review & Export <ArrowRight className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}
