/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCourses"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/{goalId}/subtree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateSubtree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/{goalId}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addChild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTerminalSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/terminal/generated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGeneratedTerminalSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/skill-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["suggestTerminalSkills"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extractions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/exam-tasks/learning-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate learning goals for exam tasks
         * @description Takes an exam as an ordered list of context/task blocks, derives the learning goals each task assesses (one LLM call per task, with all preceding context blocks attached), persists them under the course's EXAM hierarchy root and returns them per task block. Synchronous — expect a few seconds per task block.
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/competency-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuildCompetencyTree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/{goalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/courses/{courseId}/hierarchy-nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/courses/{courseId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/learning-goals/by-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBySession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/extract/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["extractStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/documents/{documentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{id}/skills-reviewed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markSkillsReviewed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateCourseRequest: {
            name: string;
            outputLanguage?: string;
            figuresEnabled?: boolean;
        };
        CourseResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            outputLanguage?: string;
            figuresEnabled?: boolean;
        };
        GoalRelationshipResponse: {
            /** @enum {string} */
            type?: "CONTRIBUTES_TO" | "SUPPORTS" | "PREREQUISITE_OF" | "OVERLAPS_WITH";
            /** Format: int64 */
            targetGoalId?: number;
            targetText?: string;
            /** Format: double */
            confidence?: number;
            /** @enum {string} */
            origin?: "HIERARCHY" | "EMBEDDING" | "LLM";
        };
        GoalSourceResponse: {
            /** Format: int64 */
            documentId?: number;
            filename?: string;
            displayName?: string;
            snippet?: string;
            /** Format: int32 */
            page?: number;
            contentAvailable?: boolean;
            grounded?: boolean;
            /** @enum {string|null} */
            groundingQuality?: "EXACT_IN_SESSION" | "EXACT_IN_DOCUMENT" | "NORMALIZED" | "FRAGMENT" | "NONE" | null;
            /** @enum {string} */
            evidenceKind?: "TEXT" | "FIGURE" | "UNSUPPORTED";
            figureDescription?: string | null;
            highlightRects?: components["schemas"]["HighlightRect"][] | null;
        };
        HierarchyPath: {
            module?: string;
            session?: string;
            exercise?: string;
            /** Format: int64 */
            sessionId?: number;
        };
        HighlightRect: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            height?: number;
        };
        LearningGoalResponse: {
            /** Format: int64 */
            id?: number;
            text?: string;
            shortLabel?: string;
            /** @enum {string} */
            kind?: "EXPLICIT" | "IMPLICIT";
            /** @enum {string} */
            role?: "SKILL" | "KNOWLEDGE";
            /** @enum {string} */
            status?: "PENDING" | "APPROVED";
            /** @enum {string} */
            origin?: "EXTRACTED" | "SYNTHESIZED" | "EXAM" | "TERMINAL" | "GAP";
            /** @enum {string} */
            creationProvenance?: "USER_CREATED" | "WIZARD_AI_SUBTREE";
            hierarchy?: components["schemas"]["HierarchyPath"];
            /** @enum {string} */
            bloomLevel?: "REMEMBER" | "UNDERSTAND" | "APPLY" | "ANALYZE" | "EVALUATE" | "CREATE";
            /** @enum {string} */
            soloLevel?: "PRESTRUCTURAL" | "UNISTRUCTURAL" | "MULTISTRUCTURAL" | "RELATIONAL" | "EXTENDED_ABSTRACT";
            /** Format: date-time */
            createdAt?: string;
            sources?: components["schemas"]["GoalSourceResponse"][];
            relationships?: components["schemas"]["GoalRelationshipResponse"][];
            /** Format: int32 */
            lectureOrder?: number;
        };
        AddChildRequest: {
            text?: string;
            shortLabel?: string;
        };
        CreateTerminalSkillRequest: {
            text?: string;
        };
        CreateGeneratedTerminalSkillRequest: {
            text?: string;
            shortLabel?: string;
        };
        SkillSuggestionResponse: {
            text?: string;
            shortLabel?: string;
        };
        ExtractionSummary: {
            /** Format: int32 */
            documentsProcessed?: number;
            /** Format: int32 */
            goalsCreated?: number;
            /** Format: int32 */
            terminalCompetencies?: number;
            /** Format: int32 */
            textSources?: number;
            /** Format: int32 */
            figureSources?: number;
            /** Format: int32 */
            unsupportedSources?: number;
        };
        ExtractionStartResponse: {
            /** Format: int64 */
            courseId?: number;
            /** @enum {string} */
            status?: "RUNNING" | "SUCCEEDED" | "FAILED";
        };
        CurrentExtractionResponse: {
            /** Format: int64 */
            courseId?: number;
            courseName?: string;
            /** @enum {string} */
            phase?: "DESCRIBING_FIGURES" | "OUTLINING" | "PARSING" | "EXTRACTING" | "CLASSIFYING" | "EMBEDDING" | "PERSISTING" | "SYNTHESIZING";
            /** Format: int32 */
            percent?: number;
            /** @enum {string} */
            status?: "RUNNING" | "SUCCEEDED" | "FAILED";
        };
        ExamBlock: {
            blockId?: string;
            /** @enum {string} */
            blockType?: "CONTEXT" | "TASK";
            taskType?: string;
            description?: string;
        };
        GenerateExamGoalsRequest: {
            blocks?: components["schemas"]["ExamBlock"][];
        };
        ExamTaskGoalsResponse: {
            blockId?: string;
            goals?: components["schemas"]["LearningGoalResponse"][];
        };
        DocumentResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            courseId?: number;
            filename?: string;
            displayName?: string;
            contentType?: string;
            /** Format: date-time */
            uploadedAt?: string;
        };
        CompetencyTreeResult: {
            /** Format: int32 */
            competencies?: number;
            /** Format: int32 */
            unmatchedGoals?: number;
        };
        UpdateCourseRequest: {
            outputLanguage?: string;
            figuresEnabled?: boolean;
        };
        UpdateLearningGoalRequest: {
            text?: string;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED";
            /** @enum {string} */
            bloomLevel?: "REMEMBER" | "UNDERSTAND" | "APPLY" | "ANALYZE" | "EVALUATE" | "CREATE";
            /** @enum {string} */
            soloLevel?: "PRESTRUCTURAL" | "UNISTRUCTURAL" | "MULTISTRUCTURAL" | "RELATIONAL" | "EXTENDED_ABSTRACT";
        };
        UpdateHierarchyNodeRequest: {
            label?: string;
        };
        HierarchyNodeResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            courseId?: number;
            /** @enum {string} */
            level?: "MODULE" | "SESSION" | "EXERCISE" | "EXAM" | "COMPETENCY";
            label?: string;
        };
        UpdateDocumentRequest: {
            displayName?: string;
        };
        CourseSummaryResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            outputLanguage?: string;
            figuresEnabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            documentCount?: number;
            /** Format: int64 */
            goalCount?: number;
            /** Format: int64 */
            skillCount?: number;
            /** Format: date-time */
            skillsReviewedAt?: string;
            /** @enum {string} */
            extractionStatus?: "RUNNING" | "SUCCEEDED" | "FAILED";
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModelCourseSummaryResponse: {
            content?: components["schemas"]["CourseSummaryResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelLearningGoalResponse: {
            content?: components["schemas"]["LearningGoalResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
        SessionGoalsResponse: {
            /** Format: int64 */
            nodeId?: number;
            /** @enum {string} */
            level?: "MODULE" | "SESSION" | "EXERCISE" | "EXAM" | "COMPETENCY";
            label?: string;
            goals?: components["schemas"]["LearningGoalResponse"][];
        };
        Snapshot: {
            /** @enum {string} */
            status?: "RUNNING" | "SUCCEEDED" | "FAILED";
            /** @enum {string} */
            phase?: "DESCRIBING_FIGURES" | "OUTLINING" | "PARSING" | "EXTRACTING" | "CLASSIFYING" | "EMBEDDING" | "PERSISTING" | "SYNTHESIZING";
            /** Format: int32 */
            completed?: number;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            percent?: number;
            model?: string;
            summary?: components["schemas"]["ExtractionSummary"];
            error?: string;
            /** Format: int32 */
            failedSessions?: number;
            failedSessionNames?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCourses: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelCourseSummaryResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
        };
    };
    generateSubtree: {
        parameters: {
            query?: {
                model?: string;
            };
            header?: never;
            path: {
                courseId: number;
                goalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningGoalResponse"];
                };
            };
        };
    };
    addChild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
                goalId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddChildRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningGoalResponse"];
                };
            };
        };
    };
    createTerminalSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTerminalSkillRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningGoalResponse"];
                };
            };
        };
    };
    createGeneratedTerminalSkill: {
        parameters: {
            query?: {
                model?: string;
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGeneratedTerminalSkillRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningGoalResponse"];
                };
            };
        };
    };
    suggestTerminalSkills: {
        parameters: {
            query?: {
                model?: string;
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkillSuggestionResponse"][];
                };
            };
        };
    };
    extract: {
        parameters: {
            query?: {
                model?: string;
                force?: boolean;
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExtractionStartResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentExtractionResponse"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate: {
        parameters: {
            query?: {
                /** @description Optional SAIA chat-model override; omit for the configured default. */
                model?: string;
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateExamGoalsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExamTaskGoalsResponse"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"][];
                };
            };
        };
    };
    upload: {
        parameters: {
            query: {
                files: string[];
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"][];
                };
            };
        };
    };
    rebuildCompetencyTree: {
        parameters: {
            query?: {
                model?: string;
                force?: boolean;
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompetencyTreeResult"];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseSummaryResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCourseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
                goalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
                goalId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLearningGoalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningGoalResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
                nodeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHierarchyNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HierarchyNodeResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
                documentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                status?: "PENDING" | "APPROVED";
                /** @description Optional extraction-tier filter: SKILL or KNOWLEDGE. Omit for all goals. */
                role?: "SKILL" | "KNOWLEDGE";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelLearningGoalResponse"];
                };
            };
        };
    };
    exportCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listBySession: {
        parameters: {
            query?: {
                /** @description Optional review-status filter: PENDING or APPROVED. Omit for all goals. */
                status?: "PENDING" | "APPROVED";
                /** @description Optional extraction-tier filter: SKILL or KNOWLEDGE. Omit for all goals. */
                role?: "SKILL" | "KNOWLEDGE";
                /** @description Optional id of a single hierarchy node (module/session/exercise) to return only that group. Read the id from the 'nodeId' field of this endpoint's unfiltered response. An unknown id yields an empty list. */
                nodeId?: number;
            };
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionGoalsResponse"][];
                };
            };
        };
    };
    extractStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: number;
                documentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    markSkillsReviewed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
